"""empty message

Revision ID: 392064635ffa
Revises: d4e20ccde8c0
Create Date: 2021-06-29 23:26:19.451548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392064635ffa'
down_revision = 'd4e20ccde8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
